language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

cache:
  directories:
    - "bin"

install:
  - "pip install flake8"

before_script: "flake8 --ignore=D203 --exclude bin/ ."

script: "python test.py"
