language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

cache:
  directories:
    - "bin"

install:
  - "pip install flake8"
  - "npm i -g eslint"

before_script: 
  - "flake8 --ignore=D203 --exclude bin/ srv/"
  - "eslint src/felt/js/**"

script: "python setup.py test"
