language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

cache:
  directories:
    - "bin"

install:
  - "pip install flake8"
  - "nvm install 8.1.4"
  - "nvm use 8.1.4"
  - "npm i -g eslint"

before_script: 
  - "flake8 ."
  - "eslint src/felt/js/**"

script: 
  - "python setup.py build"
  - "python setup.py test"
